# Generated by Django 3.1.3 on 2020-11-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20201114_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='goodtext',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='readtext',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
