# Generated by Django 3.1.3 on 2020-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_auto_20201119_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='images',
            field=models.ImageField(default='defo', upload_to=''),
        ),
    ]
