# Generated by Django 3.1.3 on 2020-11-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0009_boardmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='user',
            new_name='username',
        ),
    ]
