# Generated by Django 3.1.3 on 2020-11-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0010_auto_20201121_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='boardmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='boardmodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardapp.customusermodel'),
        ),
    ]
