# Generated by Django 3.1.3 on 2020-11-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0011_auto_20201121_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='name',
            new_name='username',
        ),
    ]
